"""
Integration fixtures run against the docker-compose services: the RAG Postgres
(5433), Dochub's Postgres (5432) for the queue, and Azurite. Each test session
gets throwaway databases and a throwaway blob container, then drops them.
"""

from __future__ import annotations

import asyncio
import base64
import hashlib
import json
import uuid
from datetime import datetime, timezone
from pathlib import Path

import httpx
import psycopg
import pytest
from azure.storage.blob.aio import BlobServiceClient

from rag_ingest.config import Settings

FIXTURES = Path(__file__).parent / "fixtures"
RAG_ADMIN = "postgresql://rag:rag@localhost:5433/postgres"
DOCHUB_ADMIN = "postgresql://dochub:dochub@localhost:5432/postgres"
AZURITE = ("DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;"
           "AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;"
           "BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;")

QUEUE_DDL = """
CREATE SCHEMA dochub;
CREATE TABLE dochub.queue_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue varchar(200) NOT NULL,
    message_id varchar(100) NOT NULL,
    subject varchar(200) NOT NULL,
    payload jsonb NOT NULL,
    session_id varchar(128),
    status integer NOT NULL,
    delivery_count integer NOT NULL,
    locked_until timestamptz,
    created_at timestamptz NOT NULL,
    completed_at timestamptz,
    error varchar(2000)
);
CREATE UNIQUE INDEX ON dochub.queue_messages (queue, message_id);
"""


def _create_db(admin: str, name: str) -> None:
    with psycopg.connect(admin, autocommit=True) as conn:
        conn.execute(f'CREATE DATABASE "{name}"')


def _drop_db(admin: str, name: str) -> None:
    with psycopg.connect(admin, autocommit=True) as conn:
        conn.execute(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)')


@pytest.fixture(scope="session")
def databases():
    suffix = uuid.uuid4().hex[:10]
    rag, queue = f"rag_test_{suffix}", f"queue_test_{suffix}"
    try:
        _create_db(RAG_ADMIN, rag)
        _create_db(DOCHUB_ADMIN, queue)
    except psycopg.OperationalError as error:
        pytest.skip(f"docker-compose Postgres not reachable: {error}")
    with psycopg.connect(DOCHUB_ADMIN.rsplit("/", 1)[0] + f"/{queue}", autocommit=True) as conn:
        conn.execute(QUEUE_DDL)
    yield {"rag": f"postgresql://rag:rag@localhost:5433/{rag}",
           "queue": f"postgresql://dochub:dochub@localhost:5432/{queue}"}
    _drop_db(RAG_ADMIN, rag)
    _drop_db(DOCHUB_ADMIN, queue)


@pytest.fixture
def settings(databases, tmp_path) -> Settings:
    return Settings(
        _env_file=None,
        rag_database_dsn=databases["rag"],
        dochub_queue_dsn=databases["queue"],
        blob_connection_string=AZURITE,
        object_container=f"rag-objects-{uuid.uuid4().hex[:8]}",
        embedding_provider="local",
        embedding_model="BAAI/bge-small-en-v1.5",
        embedding_dim=384,
        dochub_service_key="t" * 40,
        whisper_model="base",          # small and fast; the default ("small") is for production
        dochub_api_url="http://dochub.test",
        max_attempts=3,
        queue_idle_poll_seconds=0.1,
        log_json=False,
    )


@pytest.fixture(scope="session")
def local_embedder():
    """The real local model, loaded once per session."""
    from rag_ingest.llm.embedder import LocalEmbedder
    return LocalEmbedder(Settings(_env_file=None, embedding_provider="local",
                                  embedding_model="BAAI/bge-small-en-v1.5", embedding_dim=384))


class FakeDochub:
    """Records the callbacks the worker makes — a stand-in for the .NET API's endpoints."""

    def __init__(self) -> None:
        self.calls: list[tuple[str, dict]] = []
        self.fail_paths: set[str] = set()

    def handler(self, request: httpx.Request) -> httpx.Response:
        assert request.headers["X-Dochub-Service-Key"] == "t" * 40
        body = json.loads(request.content or b"{}")
        self.calls.append((request.url.path, body))
        if any(request.url.path.endswith(p) for p in self.fail_paths):
            return httpx.Response(503, text="down")
        if "/api/ingestion/artifacts/" in request.url.path:
            return httpx.Response(200, json={"artifactStatus": "Processed", "sourceStatus": "Processed"})
        return httpx.Response(200, json={"status": "ok"})

    def paths(self, suffix: str) -> list[str]:
        return [p for p, _ in self.calls if p.endswith(suffix)]


@pytest.fixture
def fake_dochub() -> FakeDochub:
    return FakeDochub()


async def upload_fixtures(settings: Settings, names: list[str], container: str) -> list[dict]:
    """Puts fixture files in Azurite the way Dochub's extractor would."""
    service = BlobServiceClient.from_connection_string(settings.blob_connection_string.get_secret_value())
    try:
        try:
            await service.create_container(container)
        except Exception:  # noqa: BLE001 — already exists
            pass
        documents = []
        for name in names:
            data = (FIXTURES / name).read_bytes()
            path = f"teams/claims/groups/claims-it/artifacts/core/20261001T000000000Z/{name}"
            await service.get_blob_client(container, path).upload_blob(data, overwrite=True)
            documents.append({
                "documentId": str(uuid.uuid5(uuid.NAMESPACE_URL, name)),
                "name": name, "relativePath": name, "blobPath": path,
                "blobUrl": f"http://127.0.0.1:10000/devstoreaccount1/{container}/{path}",
                "sizeBytes": len(data), "contentType": None,
                "checksumSha256": hashlib.sha256(data).hexdigest(), "revision": 1,
                "contentMd5": base64.b64encode(hashlib.md5(data).digest()).decode(),
                "documentVersionId": str(uuid.uuid4()), "sourceType": "Local", "externalId": None,
            })
        return documents
    finally:
        await service.close()


def process_request(documents: list[dict], container: str, artifact_id: str | None = None) -> dict:
    return {
        "sourceDocumentId": str(uuid.uuid4()), "reference": "SRC-9001",
        "artifactId": artifact_id or str(uuid.uuid4()), "organizationId": "org-test",
        "artifactName": "Claims Core Repo", "teamName": "Claims", "groupName": "Claims IT",
        "sourceType": "Local", "blobContainer": container,
        "blobPrefix": "teams/claims/groups/claims-it/artifacts/core/20261001T000000000Z",
        "documentCount": len(documents), "uploadedAt": datetime.now(timezone.utc).isoformat(),
        "documents": documents,
    }


async def enqueue(settings: Settings, body: dict, message_id: str | None = None) -> None:
    async with await psycopg.AsyncConnection.connect(settings.dochub_queue_dsn) as conn:
        await conn.execute(
            "INSERT INTO dochub.queue_messages (queue, message_id, subject, payload, status, "
            "delivery_count, created_at) VALUES (%s, %s, %s, %s, 0, 0, now())",
            (settings.process_queue, message_id or f"process-{uuid.uuid4().hex}",
             "dochub.documents.process.requested", json.dumps(body)),
        )
        await conn.commit()


async def queue_row(settings: Settings) -> dict:
    async with await psycopg.AsyncConnection.connect(settings.dochub_queue_dsn) as conn:
        row = await (await conn.execute(
            "SELECT status, delivery_count, error, locked_until FROM dochub.queue_messages ORDER BY id DESC LIMIT 1"
        )).fetchone()
    return {"status": row[0], "delivery_count": row[1], "error": row[2], "locked_until": row[3]}
